# Exception

### 1. 예외처리

###### 1-1. 예외상황 발생
    - Main01.java 예제에서 java:15 라인에서 에러가 발생한다. 
    - "안녕하세요"라는 문자열은 int로 변환할 수 없기 때문에 Console 화면과 같이
    에러가 발생한다는 내용의 메시지가 출력된다.
    - java 프로그램은 예외 상황을 만나면 그 즉시 실행을 중단하고
    강제 종료된다. 때문에 이 프로그램의 맨 마지막에 출력하려는 메시지는
    표시되지 않는다.

###### 1-2. 에러의 종류
    - 컴파일 에러
    -> 소스코드의 구문 오류로 인하여 컴파일이 불가능한 상태
    -> 이클립스에서 빨간색으로 표시되는 경우에 해당한다.
    -> 프로그램을 실행하기 전에 발견되므로 상대적으로 고치기 쉽다.

    - 런타임 에러
    -> 구문상의 에러는 없지만, 프로그램이 실행되는 과정에서
    다양한 경우의 수에 대응하지 못하여 발생하는 예외상황
    -> 런타임에러가 발생하면 프로그램은 강제로 종료된다.
    -> 우리가 프로그램의 에러라고 부르는 현상은 대부분 런타임에러에
    해당한다.

######  1-3. 런타임 에러의 종류
    - 런타임 에러에는 프로그램 자체의 구조적인 문제로 인한 논리적 오류와
    자바 가상머신 자체의 문제로 인한 오류, 그리고 예외가 있다.
    - 논리 오류 : 논리적 모순이 생기지 않도록 코드를 작성해야 한다.
    - 자바 가상머신 자체 오류 : 프로그래머가 책임질 수 있는 수준의 오류가 아니다.
    - 예외(Exception)
    -> 프로그램 실행 중에 발생할 수 있는 예기치 않은 사건으로,
    프로그래머의 노력으로 처리 할 수 있다.
    -> 자바 가상머신은 프로그램 실행중에 예외가 발생하면
    관련된 예외 클래스로부터 예외 객체를 생성하여 프로그램에서
    지정된 예외 처리 구문으로 넘긴다.
    -> 예외가 발생하면 프로그램에 지정된 예외처리 구문이 자바 가상머신에
    의해 호출되고, 이때 전달되는 예외 객체를 넘겨받아 적절한 처리를
    수행한다.

###### 1-4. java의 예외처리
    - java에서는 try ~ catch ~ finally 구문을 통해 프로그래머가
    예외 상황에 대응할 수 있도록 하고 있다.

    try{
        // 기본적으로 실행되는 부분
    } catch( 예외클래스이름 객체이름 ){
        // try블록에서 예외가 발생한 경우 
        // 이 곳으로 제어가 넘어온다.
    } finally {
        // 예외 상황의 발생 여부에 상관 없이 무조건 실행되는 부분
        // finally 블록은 생략 가능하다.
    }

    - try 블록 실행도중 catch에서 명시한 예외 클래스에 해당하는 런타임
    에러가 발생하면, try 블록을 즉시 중단하고 catch 블록이 실행 된 후,
    finally 블록이 실행된다. 
    - 예외가 발생하지 않을 경우에는 try 블록 종료 후 finally 블록이 실행된다.

###### 1-5. catch블록을 사용한 복합 에러 처리
    - catch 블록은 에러가 예상되는 상황에 대해 복수로 명시하는 것이 가능하다.
  
###### 1-6. Exception 클래스
    - java에서 예외 상황을 의미하는 모든 클래스들의 최상위 클래스
    - 이 클래스의 이름으로 catch 블록을 구성하면, 모든 예외 상황에 일괄적으로
    대응할 수는 있지만, catch 블록이 세분화 된 경우와는 달리 상황 별 개별적인
    처리는 불가능하다.
    - Exception 클래스에 대한 예외처리는 대부분 맨 마지막 catch 블록에
    명시하여 '마지막 알 수 없는 에러'를 의미하도록 구성한다.

    } catch( NumberFormatException e ){
        // 예외처리
    } catch( ArrayIndexOutOfBoundsException e ){
        // 예외처리
    } catch( Exception e ){
        // 예외처리
    } finally {

    }

###### 1-7. 에러 객체 'e'의 기능
    - e.getMessage();
    -> 간단한 에러 메시지를 리턴한다.
    -> e.getLocaliseMessage()도 같은 기능을 한다.

    - e.printStackTrace();
    -> 실제 예외 상황시에 출력되는 메시지를 강제로 출력한다.
    -> 개발자가 catch 블록 안에서 예외 상황을 분석하기 위한
    용도로 사용한다.